# Generated by Django 2.2.1 on 2019-07-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsmodel',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RenameField(
            model_name='authorsmodel',
            old_name='email_address',
            new_name='email',
        ),
    ]
