# Generated by Django 2.2.1 on 2019-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20190712_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
