# Generated by Django 2.2.1 on 2019-07-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_article_publisher_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publishers',
            new_name='publisher',
        ),
    ]
